version: '3.8'

services:
  api:
    build:
      context: "./server"
    ports:
      - "3001:8000"
    

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
