apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
        - image: docker.io/bigsidhu/sports-client:e2fe036d79dac7ccbd8872d21d5c754c76de2635
          name: sports-client
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 80
              name: 80tcpport
        - image: docker.io/bigsidhu/sports-api:e2fe036d79dac7ccbd8872d21d5c754c76de2635
          name: sports-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: 8000tcpport
      restartPolicy: Always
      dnsPolicy: Default
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sports
  namespace: default
spec:
  rules:
  - host: sports.sidhulabs.ca
    http:
      paths:
      - backend:
          service:
            name: sports-client
            port:
              number: 80
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.10.1.51
    - ip: 10.10.1.52
    - ip: 10.10.1.53
    - ip: 10.10.1.54
---
apiVersion: v1
kind: Service
metadata:
  name: sports
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: tcpport80
  selector:
    app: sports
